/*
 * Copyright 2009 Solnet Solutions Limited (http://www.solnetsolutions.co.nz/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author tohu-loader 
 *
 * (Notice included by creating a file called Copyright.drl in the import directory)
 */
package org.tohu.examples.loyalty;

import org.tohu.Group;
import org.tohu.InvalidAnswer;
import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;
import org.tohu.Note;
import org.tohu.Question;
import org.tohu.Answer;
import org.tohu.Questionnaire;
import org.tohu.support.TohuDataItemObject;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Arrays;

rule "LoyaltyCard"
dialect "mvel"
then
	Questionnaire questionnaire = new Questionnaire("LoyaltyCard");
	questionnaire.setLabel("Solnet Loyalty Card Signup");
	questionnaire.setCompletionAction("extract.pdf");
	questionnaire.setItems({"ContactDetailsPage", "JointContactDetailsPage", "DemographicDetailsPage", "MainOtherLoyaltyDetailsPage", "JointOtherLoyaltyDetailsPage"});
	questionnaire.setActiveItem("ContactDetailsPage");
	insertLogical(questionnaire);
end

declare ListEntryFact
	id : String @key
end

