/*
 * Copyright 2009 Solnet Solutions Limited (http://www.solnetsolutions.co.nz/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author tohu-loader 
 *
 * (Notice included by creating a file called Copyright.drl in the import directory)
 */
package org.tohu.examples.loyalty.loyalty_complex_app;

import java.util.Calendar;
import org.tohu.Group;
import org.tohu.InvalidAnswer;
import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;
import org.tohu.Note;
import org.tohu.Question;
import org.tohu.Answer;
import org.tohu.Questionnaire;
import org.tohu.support.TohuDataItemObject;

import org.tohu.examples.loyalty.*;

rule "Branch MainBAGroupDataItems"
salience 75
no-loop
when
	pe1 : Question(id == "budgetAirways"  );
	Answer (questionId == pe1.id , value == "true");
	q : Questionnaire(items not contains "MainBAGroupDataItems");
then
	if (q.isBranched() == false) {
		q.navigationBranch(new String[]{"MainBAGroupDataItems"}, "MainBAGroupDataItems");
	}
	else {
		q.appendItem("MainBAGroupDataItems", q.getActiveItem());
	}
	update(q);
end

rule "MainBAGroupDataItems"
dialect "mvel"
no-loop
when
	pe1 : Question(id == "budgetAirways" , answer == "true");
then
	Group aGroup = new Group("MainBAGroupDataItems");
	aGroup.setLabel("Please specify the loyalty program details.");
	aGroup.setItems({"MainBAGroup"});
	insertLogical(aGroup);
end

rule "MainBAGroup"
dialect "mvel"
no-loop
when
	$group : Group (id == "MainBAGroupDataItems");
then
	Group aGroup = new Group("MainBAGroup");
	aGroup.setLabel("8");
	aGroup.setItems({
		"mbaMembershipNumber",
		"mbaMembershipName",
		"mbaMembershipType",
		"mbaSpecialOffers"});
	insertLogical(aGroup);
end

rule "mainBAPoints"
dialect "mvel"
no-loop
when
	$group : Group (id == "MainBAGroup");
	pe1 : Question(id == "budgetAirways" , answer == "true");
then
	TohuDataItemObject aTohuDataItemObject = new TohuDataItemObject("mainBAPoints");
	aTohuDataItemObject.setAnswerType(Question.TYPE_NUMBER);
	aTohuDataItemObject.setAnswer(20L);
	aTohuDataItemObject.setCategory("Points");
	aTohuDataItemObject.setName("Main Person has a BA Card");
	insertLogical(aTohuDataItemObject);
end

rule "mbaMembershipNumber"
dialect "mvel"
no-loop
when
	$group : Group (id == "MainBAGroup");
then
	Question aQuestion = new Question("mbaMembershipNumber");
	aQuestion.setAnswerType(Question.TYPE_TEXT);
	aQuestion.setPreLabel("Membership number");
	insertLogical(aQuestion);
end

rule "mbaMembershipName"
dialect "mvel"
no-loop
when
	$group : Group (id == "MainBAGroup");
then
	Question aQuestion = new Question("mbaMembershipName");
	aQuestion.setAnswerType(Question.TYPE_TEXT);
	aQuestion.setPreLabel("Membership name");
	insertLogical(aQuestion);
end

rule "mbaMembershipType"
dialect "mvel"
no-loop
when
	$group : Group (id == "MainBAGroup");
then
	MultipleChoiceQuestion aMultipleChoiceQuestion = new MultipleChoiceQuestion("mbaMembershipType");
	aMultipleChoiceQuestion.setAnswerType(Question.TYPE_TEXT);
	aMultipleChoiceQuestion.setPreLabel("Membership Type");
	aMultipleChoiceQuestion.setPossibleAnswers({
		new PossibleAnswer("1", "Gold"),
		new PossibleAnswer("2", "Silver"),
		new PossibleAnswer("3", "Bronze")});
	aMultipleChoiceQuestion.setPresentationStyles({"radio"});
	insertLogical(aMultipleChoiceQuestion);
end

rule "mainGoldBAPoints"
dialect "mvel"
no-loop
when
	pe1 : MultipleChoiceQuestion(id == "mbaMembershipType" , answer == "1");
then
	TohuDataItemObject aTohuDataItemObject = new TohuDataItemObject("mainGoldBAPoints");
	aTohuDataItemObject.setAnswerType(Question.TYPE_NUMBER);
	aTohuDataItemObject.setAnswer(10L);
	aTohuDataItemObject.setCategory("Points");
	aTohuDataItemObject.setName("Gold BA Card");
	insertLogical(aTohuDataItemObject);
end

rule "mainSilverBAPoints"
dialect "mvel"
no-loop
when
	pe1 : MultipleChoiceQuestion(id == "mbaMembershipType" , answer == "2");
then
	TohuDataItemObject aTohuDataItemObject = new TohuDataItemObject("mainSilverBAPoints");
	aTohuDataItemObject.setAnswerType(Question.TYPE_NUMBER);
	aTohuDataItemObject.setAnswer(5L);
	aTohuDataItemObject.setCategory("Points");
	aTohuDataItemObject.setName("Silver BA Card");
	insertLogical(aTohuDataItemObject);
end

rule "mbaSpecialOffers"
dialect "mvel"
no-loop
when
	$group : Group (id == "MainBAGroup");
then
	Question aQuestion = new Question("mbaSpecialOffers");
	aQuestion.setAnswerType(Question.TYPE_BOOLEAN);
	aQuestion.setPreLabel("Do you want to receive combined special offers?");
	insertLogical(aQuestion);
end

