/*
 * Copyright 2009 Solnet Solutions Limited (http://www.solnetsolutions.co.nz/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author Derek Rendall
 */
package org.tohu.examples.loyalty

import java.util.Calendar;

import org.tohu.Group;
import org.tohu.InvalidAnswer;
import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;
import org.tohu.Note;
import org.tohu.Question;
import org.tohu.Questionnaire;

rule "Overview"
dialect "mvel"
then
	Questionnaire questionnaire = new Questionnaire("LoyaltyQuestionnaire");
	questionnaire.setLabel("Solnet Loyalty Card Signup V2");
	questionnaire.setCompletionAction("extract.pdf");
	
	questionnaire.addItem("ContactDetailsPage");
	questionnaire.addItem("DemographicDetailsPage");
	
	// This is how we enable "pages"
	questionnaire.setActiveItem("ContactDetailsPage");
	
	insertLogical(questionnaire);
end



rule "validateEmail"
dialect "java"
when
	Question(id == "email", answered == true, answer : textAnswer);
	eval(!answer.toUpperCase().matches("^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[_A-Za-z-]+)"));
then
	insertLogical(new InvalidAnswer("email", "This is not a valid email address"));
end
